const toggle=document.querySelector('.menu-toggle');
const nav=document.querySelector('#navigation');
function closeMenu(){nav.classList.remove('is-open');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Menüyü aç');}
toggle?.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';nav.classList.toggle('is-open',open);toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Menüyü kapat':'Menüyü aç');});
nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav?.classList.contains('is-open')){closeMenu();toggle.focus();}});
const venues={restoran:{kicker:'PAYLAŞILAN MEKÂNLAR',title:'Atmosferi tamamlayan ses ve görüntü.',description:'İç ve dış alanlarda dengeli müzik yayını, bölgesel seslendirme ve LED görüntü çözümleriyle mekânın kullanımını destekleyen bir altyapı.',visual:'ATMOSFER + ANLAŞILIRLIK',items:['İç ve dış alanlara uygun hoparlör seçimi','Bölgelere göre ses seviyesi yönetimi','Sunum ve içerik gösterimi için LED ekran']},sahne:{kicker:'PERFORMANS MEKÂNLARI',title:'Her performansın arkasında sağlam bir sistem.',description:'Canlı müzik, konuşma ve etkinlik senaryolarını birlikte ele alan ses, LED görüntü ve sahne bağlantı altyapıları.',visual:'PERFORMANS + ETKİ',items:['Sahne hoparlörleri, monitörler ve mikser','El, yaka, kafa ve enstrüman mikrofonları','Podyum, stagebox ve AV bağlantı panelleri']},kurumsal:{kicker:'TOPLANTI VE ÖĞRENME',title:'Fikrinizi herkes duysun. İçeriğinizi herkes görsün.',description:'Toplantı, sunum ve eğitim kullanımına uygun ses ve görüntü sistemlerini mekânın kapasitesi ve mevcut altyapısı etrafında planlıyoruz.',visual:'İLETİŞİM + NETLİK',items:['Konuşma odaklı mikrofon ve seslendirme','Sunumlar için LED görüntü çözümleri','Bağlantı düzeni, devreye alma ve eğitim']}};
const tabs=[...document.querySelectorAll('[data-venue]')];
function activate(tab){const item=venues[tab.dataset.venue];tabs.forEach(t=>{t.setAttribute('aria-selected',String(t===tab));t.tabIndex=t===tab?0:-1;});document.querySelector('#venue-panel').setAttribute('aria-labelledby',tab.id);for(const [id,value] of [['venue-kicker',item.kicker],['venue-title',item.title],['venue-description',item.description],['venue-visual-label',item.visual]])document.getElementById(id).textContent=value;document.querySelector('#venue-list').replaceChildren(...item.items.map(text=>{const li=document.createElement('li');li.textContent=text;return li;}));}
tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>activate(tab));tab.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();tabs[next].focus();activate(tabs[next]);}});});
const form=document.querySelector('#project-form');let requestText='';
form?.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const values=new FormData(form);requestText=`PERMAS proje talebi\n\nAd Soyad: ${values.get('name')}\nKurum: ${values.get('company')}\nE-posta: ${values.get('email')}\nÇözüm: ${values.get('solution')}\n\nProje açıklaması:\n${values.get('message')}`;const subject='PERMAS Proje Talebi — '+values.get('solution');window.location.href='mailto:info@permas.com.tr?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(requestText);document.querySelector('#form-status').textContent='E-posta uygulamanızda taslağı göndererek talebinizi tamamlayın. Uygulama açılmazsa metni kopyalayıp info@permas.com.tr adresine gönderebilirsiniz.';document.querySelector('#copy-request').hidden=false;});
document.querySelector('#copy-request')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(requestText);document.querySelector('#form-status').textContent='Talep metni kopyalandı. info@permas.com.tr adresine e-posta ile gönderebilirsiniz.';}catch{document.querySelector('#form-status').textContent='Kopyalama kullanılamıyor. Doğrudan info@permas.com.tr adresine yazabilir veya bizi arayabilirsiniz.'}});
const year=document.querySelector('#year');if(year)year.textContent=new Date().getFullYear();
